package dev.accessscope.scanner.recorder

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Regressione [MaestroYamlImporter] (Maestro Beta).
 */
class MaestroYamlImporterTest {

    @Test
    fun parse_exportRoundTripSubset() {
        val yaml = """
            # Generated by AccessScope Maestro (Beta)
            appId: "com.example.app"
            name: "Login"
            tags:
              - accessscope
              - beta
            ---
            - launchApp
            - waitForAnimationToEnd
            - tapOn:
                id: "username"
            - inputText: "user"
            - hideKeyboard
            - tapOn: "CONTINUA"
            - scroll
            - back
        """.trimIndent()

        val result = MaestroYamlImporter.parse(yaml)
        assertTrue(result is MaestroImportResult.Success)
        val success = result as MaestroImportResult.Success
        assertEquals("com.example.app", success.appId)
        assertEquals("Login", success.name)
        assertTrue(success.actions.any { it is RecordedAction.LaunchApp })
        // Round-trip exporter: `- tapOn: {id}` + `- inputText:` è UNA InputText con viewId (M1-A3).
        assertTrue(
            success.actions.any {
                it is RecordedAction.InputText && it.viewId == "username" && it.text == "user"
            },
        )
        assertTrue(success.actions.none { it is RecordedAction.Tap && it.viewId == "username" })
        assertTrue(success.actions.any { it is RecordedAction.HideKeyboard })
        assertTrue(success.actions.any { it is RecordedAction.Tap && it.text == "CONTINUA" })
    }

    @Test
    fun parse_rejectsUnknownCommand() {
        val yaml = """
            appId: "com.example"
            ---
            - launchApp
            - unknownMaestroCommand
        """.trimIndent()
        val result = MaestroYamlImporter.parse(yaml)
        assertTrue(result is MaestroImportResult.Failure)
    }

    @Test
    fun parse_newCommands_doubleTapSwipeAssertPressKey() {
        val yaml = """
            appId: "com.example"
            name: "Extras"
            ---
            - launchApp
            - doubleTapOn: "Zoom"
            - eraseText:
                id: "username"
            - swipe:
                start: "50%,80%"
                end: "50%,20%"
            - pressKey: Enter
            - assertVisible:
                id: "home"
            - assertNotVisible: "Loading"
            - scrollUntilVisible:
                text: "POLIZZA"
                direction: DOWN
            - openLink: "https://example.com"
            - stopApp
        """.trimIndent()
        val result = MaestroYamlImporter.parse(yaml)
        assertTrue(result is MaestroImportResult.Success)
        val actions = (result as MaestroImportResult.Success).actions
        assertTrue(actions.any { it is RecordedAction.DoubleTap && it.text == "Zoom" })
        assertTrue(actions.any { it is RecordedAction.EraseText && it.viewId == "username" })
        assertTrue(actions.any { it is RecordedAction.Swipe })
        assertTrue(actions.any { it is RecordedAction.PressKey && it.key == "Enter" })
        assertTrue(actions.any { it is RecordedAction.AssertVisible && it.viewId == "home" })
        assertTrue(actions.any { it is RecordedAction.AssertNotVisible && it.text == "Loading" })
        assertTrue(actions.any { it is RecordedAction.ScrollUntilVisible && it.visibleText == "POLIZZA" })
        assertTrue(actions.any { it is RecordedAction.OpenLink && it.url == "https://example.com" })
        assertTrue(actions.any { it is RecordedAction.StopApp })
    }
}
