/**
 * Esporta [RecordedAction] in YAML Maestro (Beta).
 */
package dev.accessscope.scanner.recorder

import dev.accessscope.scanner.recorder.intelligence.ScanIntelligenceBundle
import dev.accessscope.scanner.recorder.model.FlowTelemetry
import dev.accessscope.scanner.recorder.model.StepExecutionMode
import dev.accessscope.scanner.recorder.optimization.selector.SelectorRanker

/**
 * Generatore YAML compatibile con Maestro CLI.
 *
 * Si aspetta azioni già ottimizzate ([FlowOptimizer.optimize]) e passate anche da
 * [FlowOptimizer.sanitizeForPlay] (vedi `FlowStore.writeArtifacts`) — la stessa trasformazione
 * applicata al Play in-app, così il YAML esportato riflette esattamente ciò che gira dal vivo
 * invece di poter divergere. Non ri-ottimizza da sé.
 */
object MaestroYamlExporter {

    /**
     * Costruisce il documento YAML completo.
     *
     * @param appId Package Android target.
     * @param flowName Nome leggibile del flusso.
     * @param actions Azioni (preferibilmente ottimizzate; può includere già un LaunchApp).
     * @return Testo YAML con header Beta.
     */
    fun export(
        appId: String,
        flowName: String,
        actions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle? = null,
        telemetry: FlowTelemetry? = null,
    ): String {
        val steps = mutableListOf<String>()
        val hasLaunch = actions.any { it is RecordedAction.LaunchApp }
        if (!hasLaunch) {
            steps += "- launchApp"
            steps += "- waitForAnimationToEnd"
        }
        var i = 0
        while (i < actions.size) {
            val action = actions[i]
            if (action is RecordedAction.Tap &&
                MaestroSelectorHeuristics.isSystemChromeTap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                )
            ) {
                i++
                continue
            }
            if (action is RecordedAction.LongPress &&
                MaestroSelectorHeuristics.isSystemChromeTap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                )
            ) {
                i++
                continue
            }
            // eraseText su un campo specifico è due comandi Maestro (tapOn per portare il
            // focus, poi eraseText senza selettore — eraseText non accetta `id:`).
            if (action is RecordedAction.EraseText && !action.viewId.isNullOrBlank()) {
                val shortId = MaestroSelectorHeuristics.shortViewId(action.viewId)
                if (!shortId.isNullOrBlank()) {
                    steps += buildString {
                        appendLine("- tapOn:")
                        append("    id: ${yamlString(escapeMaestroText(shortId))}")
                    }
                    steps += "- eraseText"
                    i++
                    continue
                }
            }
            steps += formatAction(action, actions, scanIntel, telemetry)
            i++
        }
        val usesPin = actions.any { it is RecordedAction.InputText && isPinSecret(it) }
        val usesPassword = actions.any { it is RecordedAction.InputText && isPasswordSecret(it) }
        return buildString {
            appendLine("# Generated by AccessScope Maestro (Beta)")
            appendLine("# Review selectors (id/text/point) before CI use.")
            if (usesPin || usesPassword) {
                appendLine("# Secrets resolved from env — pass with: maestro test -e PIN=... -e PASSWORD=... flow.yaml")
            }
            appendLine("appId: ${yamlString(appId)}")
            appendLine("name: ${yamlString(flowName)}")
            appendLine("tags:")
            appendLine("  - accessscope")
            appendLine("  - beta")
            if (usesPin || usesPassword) {
                appendLine("env:")
                if (usesPin) appendLine("  PIN: \"0000\"")
                if (usesPassword) appendLine("  PASSWORD: \"changeme\"")
            }
            appendLine("---")
            steps.forEach { appendLine(it) }
        }
    }

    /**
     * Classificazione segreto identica a quella usata in [formatAction] per `InputText`
     * (stessa logica, per evitare che header `env:` e placeholder esportato divergano).
     */
    private fun isSecretInput(action: RecordedAction.InputText): Boolean =
        action.isPassword ||
            action.text == "****" ||
            action.text == CredentialVault.PLACEHOLDER_PASSWORD ||
            action.text == CredentialVault.PLACEHOLDER_PIN ||
            MaestroSelectorHeuristics.isPinLikeField(action.viewId)

    private fun isPinSecret(action: RecordedAction.InputText): Boolean =
        isSecretInput(action) &&
            (MaestroSelectorHeuristics.isPinLikeField(action.viewId) || action.text == CredentialVault.PLACEHOLDER_PIN)

    private fun isPasswordSecret(action: RecordedAction.InputText): Boolean =
        isSecretInput(action) && !isPinSecret(action)

    /**
     * Conta gli step eseguibili (linee comando YAML generate).
     */
    fun countSteps(actions: List<RecordedAction>): Int {
        val base = if (actions.any { it is RecordedAction.LaunchApp }) 0 else 2
        return base + actions.sumOf { actionStepCount(it) }
    }

    private fun actionStepCount(action: RecordedAction): Int = when (action) {
        is RecordedAction.Wait -> 1
        else -> 1
    }

    private fun formatAction(
        action: RecordedAction,
        allActions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle?,
        telemetry: FlowTelemetry?,
    ): String = when (action) {
        is RecordedAction.LaunchApp -> "- launchApp"
        is RecordedAction.Tap -> formatTap(
            "tapOn",
            action,
            allActions,
            scanIntel,
            telemetry,
        )
        is RecordedAction.DoubleTap -> formatTap(
            "doubleTapOn",
            action.viewId,
            action.text,
            action.contentDescription,
            action.pointPercentX,
            action.pointPercentY,
            optional = false,
            idOnly = !MaestroSelectorHeuristics.shortViewId(action.viewId).isNullOrBlank() &&
                action.pointPercentX == null,
        )
        is RecordedAction.LongPress -> formatTap(
            "longPressOn",
            action.viewId,
            action.text,
            action.contentDescription,
            action.pointPercentX,
            action.pointPercentY,
            optional = false,
            idOnly = SelectorRanker.shouldExportIdOnly(
                RecordedAction.Tap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                    action.pointPercentX,
                    action.pointPercentY,
                ),
                allActions,
                scanIntel,
                telemetry,
            ),
        )
        is RecordedAction.InputText -> {
            val shortId = MaestroSelectorHeuristics.shortViewId(action.viewId)
            val isSecret = isSecretInput(action)
            val placeholder = when {
                isPinSecret(action) -> CredentialVault.PLACEHOLDER_PIN
                isSecret -> CredentialVault.PLACEHOLDER_PASSWORD
                else -> action.text
            }
            when {
                isSecret && !shortId.isNullOrBlank() -> buildString {
                    appendLine("- tapOn:")
                    appendLine("    id: ${yamlString(escapeMaestroText(shortId))}")
                    appendLine("- inputText: ${yamlString(placeholder)}")
                    append("# secret placeholder — resolve via env / CredentialVault")
                }.trimEnd()
                isSecret -> "- inputText: ${yamlString(placeholder)}"
                !shortId.isNullOrBlank() -> buildString {
                    appendLine("- tapOn:")
                    appendLine("    id: ${yamlString(escapeMaestroText(shortId))}")
                    append("- inputText: ${yamlString(action.text)}")
                }.trimEnd()
                else -> "- inputText: ${yamlString(action.text)}"
            }
        }
        is RecordedAction.EraseText -> {
            // Il caso con viewId è già intercettato in export() (tapOn + eraseText:
            // eraseText non accetta `id:` in Maestro reale). Qui resta solo il caso bare.
            "- eraseText"
        }
        is RecordedAction.Scroll -> "- scroll"
        is RecordedAction.ScrollUntilVisible -> formatScrollUntilVisible(action)
        is RecordedAction.Swipe -> buildString {
            appendLine("- swipe:")
            appendLine("    start: \"${fmtPercent(action.startPercentX)}%,${fmtPercent(action.startPercentY)}%\"")
            append("    end: \"${fmtPercent(action.endPercentX)}%,${fmtPercent(action.endPercentY)}%\"")
        }.trimEnd()
        is RecordedAction.Back -> "- back"
        is RecordedAction.PressKey -> formatPressKey(action.key)
        is RecordedAction.AssertVisible -> formatAssert("assertVisible", action.viewId, action.text)
        is RecordedAction.AssertNotVisible -> formatAssert("assertNotVisible", action.viewId, action.text)
        is RecordedAction.OpenLink -> "- openLink: ${yamlString(action.url)}"
        is RecordedAction.StopApp -> "- stopApp"
        is RecordedAction.HideKeyboard -> "- hideKeyboard"
        is RecordedAction.WaitForAnimation -> {
            if (action.timeoutMs != null) {
                buildString {
                    appendLine("- waitForAnimationToEnd:")
                    append("    timeout: ${action.timeoutMs}")
                }.trimEnd()
            } else {
                "- waitForAnimationToEnd"
            }
        }
        is RecordedAction.Wait -> formatWait(action)
        is RecordedAction.RawMaestroYaml -> formatRawYaml(action.yamlLines)
    }

    /** Chiavi valide per `pressKey` (enum Maestro CLI, verificato con `maestro check-syntax`). */
    private val VALID_PRESS_KEYS = setOf(
        "Enter", "Backspace", "Back", "Home", "Lock",
        "Volume Up", "Volume Down", "Recent Apps", "Power", "Tab",
    )

    /**
     * Valida `key` contro l'enum Maestro reale; una chiave sconosciuta romperebbe il
     * comando a runtime senza un errore di parsing chiaro, quindi si ripiega su `Enter`
     * con un commento invece di esportare un valore non validato.
     */
    private fun formatPressKey(key: String): String {
        val normalized = VALID_PRESS_KEYS.firstOrNull { it.equals(key, ignoreCase = true) }
        if (normalized != null) return "- pressKey: $normalized"
        return "- pressKey: Enter\n# chiave originale non riconosciuta da Maestro: \"$key\""
    }

    /**
     * Esporta `scrollUntilVisible` con id/testo (annidati sotto `element:`, come richiesto
     * dallo schema Maestro reale — verificato con `maestro check-syntax`) e direzione.
     */
    private fun formatScrollUntilVisible(action: RecordedAction.ScrollUntilVisible): String {
        val shortId = MaestroSelectorHeuristics.shortViewId(action.visibleId)
        val safeText = action.visibleText?.takeIf { it.isNotBlank() }
        if (shortId.isNullOrBlank() && safeText == null) {
            return "# SKIPPED scrollUntilVisible: nessun selettore disponibile — ripeti PICK."
        }
        return buildString {
            appendLine("- scrollUntilVisible:")
            appendLine("    element:")
            when {
                !shortId.isNullOrBlank() -> appendLine("      id: ${yamlString(escapeMaestroText(shortId))}")
                else -> appendLine("      text: ${yamlString(escapeMaestroText(safeText!!))}")
            }
            append("    direction: ${action.direction.name}")
        }.trimEnd()
    }

    /**
     * Esporta assertVisible / assertNotVisible (id o testo).
     */
    private fun formatAssert(command: String, viewId: String?, text: String?): String {
        val shortId = MaestroSelectorHeuristics.shortViewId(viewId)
        val safeText = text?.takeIf { it.isNotBlank() }
        return when {
            !shortId.isNullOrBlank() -> buildString {
                appendLine("- $command:")
                append("    id: ${yamlString(escapeMaestroText(shortId))}")
            }.trimEnd()
            safeText != null -> "- $command: ${yamlString(escapeMaestroText(safeText))}"
            else -> "# SKIPPED $command: nessun selettore disponibile — ripeti PICK."
        }
    }

    /**
     * Emette linee YAML grezze assicurando il prefisso `- `.
     */
    private fun formatRawYaml(yamlLines: String): String {
        val lines = yamlLines.lines().map { it.trimEnd() }.filter { it.isNotBlank() }
        if (lines.isEmpty()) return "- # empty raw yaml"
        return lines.joinToString("\n") { line ->
            val trimmed = line.trimStart()
            if (trimmed.startsWith("-")) line else "- $trimmed"
        }
    }

    private fun formatWait(action: RecordedAction.Wait): String {
        // Come tutti gli altri comandi: id SHORT (non package:id/name completo), altrimenti
        // l'escape regex produce un id illeggibile e incoerente col resto dell'export.
        val id = MaestroSelectorHeuristics.shortViewId(action.visibleId)?.takeIf { it.isNotBlank() }
        val text = action.visibleText?.takeIf { it.isNotBlank() }
        return when {
            id != null || text != null -> buildString {
                appendLine("- extendedWaitUntil:")
                appendLine("    visible:")
                when {
                    id != null -> appendLine("      id: ${yamlString(escapeMaestroText(id))}")
                    else -> appendLine("      text: ${yamlString(escapeMaestroText(text!!))}")
                }
                append("    timeout: ${action.timeoutMs}")
            }.trimEnd()
            else -> buildString {
                appendLine("- waitForAnimationToEnd:")
                append("    timeout: ${action.timeoutMs}")
            }.trimEnd()
        }
    }

    private fun formatTap(
        command: String,
        action: RecordedAction.Tap,
        allActions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle?,
        telemetry: FlowTelemetry?,
    ): String {
        val chain = action.selectorChain.ifEmpty {
            SelectorRanker.buildChain(action, allActions, scanIntel, telemetry)
        }
        val primary = chain.firstOrNull()
        val idOnly = SelectorRanker.shouldExportIdOnly(action, allActions, scanIntel, telemetry)
        val body = formatTap(
            command,
            primary?.viewId ?: action.viewId,
            primary?.text ?: action.text,
            primary?.contentDescription ?: action.contentDescription,
            primary?.pointPercentX ?: action.pointPercentX,
            primary?.pointPercentY ?: action.pointPercentY,
            optional = action.executionMode == StepExecutionMode.Optional,
            idOnly = idOnly,
        )
        if (chain.size <= 1) return body
        val fallbackComment = chain.drop(1).joinToString(" | ") { c ->
            when {
                !c.viewId.isNullOrBlank() -> "id=${MaestroSelectorHeuristics.shortViewId(c.viewId)}"
                !c.text.isNullOrBlank() -> "text=${c.text}"
                !c.contentDescription.isNullOrBlank() -> "cd=${c.contentDescription}"
                c.pointPercentX != null -> "point"
                else -> "?"
            }
        }
        return "$body\n# fallbackChain: $fallbackComment"
    }

    private fun formatTap(
        command: String,
        viewId: String?,
        text: String?,
        contentDescription: String?,
        pointX: Float?,
        pointY: Float?,
        optional: Boolean = false,
        idOnly: Boolean = false,
    ): String {
        val shortId = viewId?.substringAfterLast('/')?.takeIf { it.isNotBlank() }
        val safeText = text?.takeIf { it.isNotBlank() }
        val safeCd = contentDescription?.takeIf { it.isNotBlank() }
        val hasSelector = shortId != null || safeText != null || safeCd != null ||
            (pointX != null && pointY != null)
        if (!hasSelector) {
            return "# SKIPPED $command: nessun selettore disponibile — ripeti PICK sull'elemento."
        }
        val body = when {
            shortId != null && (idOnly || pointX == null) -> buildString {
                appendLine("- $command:")
                append("    id: ${yamlString(escapeMaestroText(shortId))}")
            }.trimEnd()
            safeText != null -> "- $command: ${yamlString(escapeMaestroText(safeText))}"
            safeCd != null -> "- $command: ${yamlString(escapeMaestroText(safeCd))}"
            else -> buildString {
                appendLine("- $command:")
                append("    point: \"${fmtPercent(pointX!!)}%,${fmtPercent(pointY!!)}%\"")
            }.trimEnd()
        }
        if (!optional) return body
        return when {
            body.startsWith("- $command:") && body.contains("\n") -> body + "\n    optional: true"
            else -> buildString {
                appendLine("- $command:")
                appendLine("    text: ${yamlString(escapeMaestroText(safeText ?: safeCd!!))}")
                append("    optional: true")
            }.trimEnd()
        }
    }

    /** Percentuali intere: Maestro non accetta decimali su `swipe.start/end` (verificato con `maestro check-syntax`). */
    private fun fmtPercent(v: Float): String = Math.round(v).toString()

    private val MAESTRO_REGEX_METACHARS = "\\.^$*+?()[]{}|".toCharArray()

    /**
     * Effettua l'escape dei metacaratteri regex prima di esportare un testo/id come selettore.
     *
     * Maestro tratta `text:`/`id:` come regex full-match: un'etichetta con parentesi o punti
     * (es. "Accedi (Beta)") altrimenti fallisce il match a runtime senza errore di parsing —
     * il tipo di rottura più frequente per un QA team che riusa lo YAML esportato.
     */
    private fun escapeMaestroText(value: String): String = buildString {
        for (c in value) {
            if (c in MAESTRO_REGEX_METACHARS) append('\\')
            append(c)
        }
    }

    private fun yamlString(value: String): String {
        val escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
