/**
 * Esporta [RecordedAction] in YAML Maestro (Beta).
 */
package dev.accessscope.scanner.recorder

import dev.accessscope.scanner.recorder.intelligence.ScanIntelligenceBundle
import dev.accessscope.scanner.recorder.model.FlowTelemetry
import dev.accessscope.scanner.recorder.model.StepExecutionMode
import dev.accessscope.scanner.recorder.optimization.selector.SelectorRanker

/**
 * Generatore YAML compatibile con Maestro CLI.
 *
 * Si aspetta azioni già ottimizzate ([FlowOptimizer.optimize]); non ri-ottimizza.
 */
object MaestroYamlExporter {

    /**
     * Costruisce il documento YAML completo.
     *
     * @param appId Package Android target.
     * @param flowName Nome leggibile del flusso.
     * @param actions Azioni (preferibilmente ottimizzate; può includere già un LaunchApp).
     * @return Testo YAML con header Beta.
     */
    fun export(
        appId: String,
        flowName: String,
        actions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle? = null,
        telemetry: FlowTelemetry? = null,
    ): String {
        val steps = mutableListOf<String>()
        val hasLaunch = actions.any { it is RecordedAction.LaunchApp }
        if (!hasLaunch) {
            steps += "- launchApp"
            steps += "- waitForAnimationToEnd"
        }
        actions.forEach { action ->
            if (action is RecordedAction.Tap &&
                MaestroSelectorHeuristics.isSystemChromeTap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                )
            ) {
                return@forEach
            }
            if (action is RecordedAction.LongPress &&
                MaestroSelectorHeuristics.isSystemChromeTap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                )
            ) {
                return@forEach
            }
            steps += formatAction(action, actions, scanIntel, telemetry)
        }
        return buildString {
            appendLine("# Generated by AccessScope Maestro (Beta)")
            appendLine("# Review selectors (id/text/point) before CI use.")
            appendLine("# Secrets: set env ${'$'}{PIN} / ${'$'}{PASSWORD} (see CredentialVault in-app).")
            appendLine("appId: ${yamlString(appId)}")
            appendLine("name: ${yamlString(flowName)}")
            appendLine("tags:")
            appendLine("  - accessscope")
            appendLine("  - beta")
            appendLine("---")
            steps.forEach { appendLine(it) }
        }
    }

    /**
     * Conta gli step eseguibili (linee comando YAML generate).
     */
    fun countSteps(actions: List<RecordedAction>): Int {
        val base = if (actions.any { it is RecordedAction.LaunchApp }) 0 else 2
        return base + actions.sumOf { actionStepCount(it) }
    }

    private fun actionStepCount(action: RecordedAction): Int = when (action) {
        is RecordedAction.Wait -> 1
        else -> 1
    }

    private fun formatAction(
        action: RecordedAction,
        allActions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle?,
        telemetry: FlowTelemetry?,
    ): String = when (action) {
        is RecordedAction.LaunchApp -> "- launchApp"
        is RecordedAction.Tap -> formatTap(
            "tapOn",
            action,
            allActions,
            scanIntel,
            telemetry,
        )
        is RecordedAction.DoubleTap -> formatTap(
            "doubleTapOn",
            action.viewId,
            action.text,
            action.contentDescription,
            action.pointPercentX,
            action.pointPercentY,
            optional = false,
            idOnly = !MaestroSelectorHeuristics.shortViewId(action.viewId).isNullOrBlank() &&
                action.pointPercentX == null,
        )
        is RecordedAction.LongPress -> formatTap(
            "longPressOn",
            action.viewId,
            action.text,
            action.contentDescription,
            action.pointPercentX,
            action.pointPercentY,
            optional = false,
            idOnly = SelectorRanker.shouldExportIdOnly(
                RecordedAction.Tap(
                    action.packageName,
                    action.viewId,
                    action.text,
                    action.contentDescription,
                    action.pointPercentX,
                    action.pointPercentY,
                ),
                allActions,
                scanIntel,
                telemetry,
            ),
        )
        is RecordedAction.InputText -> {
            val shortId = MaestroSelectorHeuristics.shortViewId(action.viewId)
            val isSecret = action.isPassword ||
                action.text == "****" ||
                action.text == CredentialVault.PLACEHOLDER_PASSWORD ||
                action.text == CredentialVault.PLACEHOLDER_PIN ||
                MaestroSelectorHeuristics.isPinLikeField(action.viewId)
            val placeholder = when {
                MaestroSelectorHeuristics.isPinLikeField(action.viewId) ||
                    action.text == CredentialVault.PLACEHOLDER_PIN -> CredentialVault.PLACEHOLDER_PIN
                isSecret -> CredentialVault.PLACEHOLDER_PASSWORD
                else -> action.text
            }
            when {
                isSecret && !shortId.isNullOrBlank() -> buildString {
                    appendLine("- tapOn:")
                    appendLine("    id: ${yamlString(shortId)}")
                    appendLine("- inputText: ${yamlString(placeholder)}")
                    append("# secret placeholder — resolve via env / CredentialVault")
                }.trimEnd()
                isSecret -> "- inputText: ${yamlString(placeholder)}"
                !shortId.isNullOrBlank() -> buildString {
                    appendLine("- tapOn:")
                    appendLine("    id: ${yamlString(shortId)}")
                    append("- inputText: ${yamlString(action.text)}")
                }.trimEnd()
                else -> "- inputText: ${yamlString(action.text)}"
            }
        }
        is RecordedAction.EraseText -> {
            val shortId = MaestroSelectorHeuristics.shortViewId(action.viewId)
            if (!shortId.isNullOrBlank()) {
                buildString {
                    appendLine("- eraseText:")
                    append("    id: ${yamlString(shortId)}")
                }.trimEnd()
            } else {
                "- eraseText"
            }
        }
        is RecordedAction.Scroll -> "- scroll"
        is RecordedAction.ScrollUntilVisible -> formatScrollUntilVisible(action)
        is RecordedAction.Swipe -> buildString {
            appendLine("- swipe:")
            appendLine("    start: \"${fmt(action.startPercentX)}%,${fmt(action.startPercentY)}%\"")
            append("    end: \"${fmt(action.endPercentX)}%,${fmt(action.endPercentY)}%\"")
        }.trimEnd()
        is RecordedAction.Back -> "- back"
        is RecordedAction.PressKey -> "- pressKey: ${action.key}"
        is RecordedAction.AssertVisible -> formatAssert("assertVisible", action.viewId, action.text)
        is RecordedAction.AssertNotVisible -> formatAssert("assertNotVisible", action.viewId, action.text)
        is RecordedAction.OpenLink -> "- openLink: ${yamlString(action.url)}"
        is RecordedAction.StopApp -> "- stopApp"
        is RecordedAction.HideKeyboard -> "- hideKeyboard"
        is RecordedAction.WaitForAnimation -> {
            if (action.timeoutMs != null) {
                buildString {
                    appendLine("- waitForAnimationToEnd:")
                    append("    timeout: ${action.timeoutMs}")
                }.trimEnd()
            } else {
                "- waitForAnimationToEnd"
            }
        }
        is RecordedAction.Wait -> formatWait(action)
        is RecordedAction.RawMaestroYaml -> formatRawYaml(action.yamlLines)
    }

    /**
     * Esporta `scrollUntilVisible` con id/testo e direzione.
     */
    private fun formatScrollUntilVisible(action: RecordedAction.ScrollUntilVisible): String {
        val shortId = MaestroSelectorHeuristics.shortViewId(action.visibleId)
        return buildString {
            appendLine("- scrollUntilVisible:")
            when {
                !shortId.isNullOrBlank() -> appendLine("    id: ${yamlString(shortId)}")
                !action.visibleText.isNullOrBlank() ->
                    appendLine("    text: ${yamlString(action.visibleText)}")
                else -> appendLine("    text: \"unknown\"")
            }
            append("    direction: ${action.direction.name}")
        }.trimEnd()
    }

    /**
     * Esporta assertVisible / assertNotVisible (id o testo).
     */
    private fun formatAssert(command: String, viewId: String?, text: String?): String {
        val shortId = MaestroSelectorHeuristics.shortViewId(viewId)
        return when {
            !shortId.isNullOrBlank() -> buildString {
                appendLine("- $command:")
                append("    id: ${yamlString(shortId)}")
            }.trimEnd()
            !text.isNullOrBlank() -> "- $command: ${yamlString(text)}"
            else -> "- $command: \"unknown\""
        }
    }

    /**
     * Emette linee YAML grezze assicurando il prefisso `- `.
     */
    private fun formatRawYaml(yamlLines: String): String {
        val lines = yamlLines.lines().map { it.trimEnd() }.filter { it.isNotBlank() }
        if (lines.isEmpty()) return "- # empty raw yaml"
        return lines.joinToString("\n") { line ->
            val trimmed = line.trimStart()
            if (trimmed.startsWith("-")) line else "- $trimmed"
        }
    }

    private fun formatWait(action: RecordedAction.Wait): String {
        val id = action.visibleId?.takeIf { it.isNotBlank() }
        val text = action.visibleText?.takeIf { it.isNotBlank() }
        return when {
            id != null || text != null -> buildString {
                appendLine("- extendedWaitUntil:")
                appendLine("    visible:")
                when {
                    id != null -> appendLine("      id: ${yamlString(id)}")
                    else -> appendLine("      text: ${yamlString(text!!)}")
                }
                append("    timeout: ${action.timeoutMs}")
            }.trimEnd()
            else -> buildString {
                appendLine("- waitForAnimationToEnd:")
                append("    timeout: ${action.timeoutMs}")
            }.trimEnd()
        }
    }

    private fun formatTap(
        command: String,
        action: RecordedAction.Tap,
        allActions: List<RecordedAction>,
        scanIntel: ScanIntelligenceBundle?,
        telemetry: FlowTelemetry?,
    ): String {
        val chain = action.selectorChain.ifEmpty {
            SelectorRanker.buildChain(action, allActions, scanIntel, telemetry)
        }
        val primary = chain.firstOrNull()
        val idOnly = SelectorRanker.shouldExportIdOnly(action, allActions, scanIntel, telemetry)
        val body = formatTap(
            command,
            primary?.viewId ?: action.viewId,
            primary?.text ?: action.text,
            primary?.contentDescription ?: action.contentDescription,
            primary?.pointPercentX ?: action.pointPercentX,
            primary?.pointPercentY ?: action.pointPercentY,
            optional = action.executionMode == StepExecutionMode.Optional,
            idOnly = idOnly,
        )
        if (chain.size <= 1) return body
        val fallbackComment = chain.drop(1).joinToString(" | ") { c ->
            when {
                !c.viewId.isNullOrBlank() -> "id=${MaestroSelectorHeuristics.shortViewId(c.viewId)}"
                !c.text.isNullOrBlank() -> "text=${c.text}"
                !c.contentDescription.isNullOrBlank() -> "cd=${c.contentDescription}"
                c.pointPercentX != null -> "point"
                else -> "?"
            }
        }
        return "$body\n# fallbackChain: $fallbackComment"
    }

    private fun formatTap(
        command: String,
        viewId: String?,
        text: String?,
        contentDescription: String?,
        pointX: Float?,
        pointY: Float?,
        optional: Boolean = false,
        idOnly: Boolean = false,
    ): String {
        val shortId = viewId?.substringAfterLast('/')?.takeIf { it.isNotBlank() }
        val body = when {
            shortId != null && (idOnly || pointX == null) -> buildString {
                appendLine("- $command:")
                append("    id: ${yamlString(shortId)}")
            }.trimEnd()
            !text.isNullOrBlank() -> "- $command: ${yamlString(text)}"
            !contentDescription.isNullOrBlank() -> "- $command: ${yamlString(contentDescription)}"
            pointX != null && pointY != null -> buildString {
                appendLine("- $command:")
                append("    point: \"${fmt(pointX)}%,${fmt(pointY)}%\"")
            }.trimEnd()
            else -> "- $command: \"unknown\""
        }
        if (!optional) return body
        return when {
            body.startsWith("- $command:") && body.contains("\n") -> body + "\n    optional: true"
            else -> buildString {
                appendLine("- $command:")
                appendLine("    text: ${yamlString(text ?: contentDescription ?: "unknown")}")
                append("    optional: true")
            }.trimEnd()
        }
    }

    private fun fmt(v: Float): String = "%.1f".format(java.util.Locale.US, v)

    private fun yamlString(value: String): String {
        val escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
